name: Publish CI

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'What type of task to run'
        required: true
        default: 'curseforge'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle and publish
        run: ./gradlew build publishCurseForge
        env:
          CURSE_API: ${{ secrets.CURSE_API }}
      - uses: actions/upload-artifact@v3
        with:
          name: 'Prebuilt Artifacts'
          path: build/libs